spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            clientId: 221525590841-pt27k7u5atck4n6em39cqrspi9gp9vb8.apps.googleusercontent.com
            scope: profile,email

